#!/usr/bin/env sh
branch="$(git rev-parse --abbrev-ref HEAD)"

# prevent direct commit to main branch
if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
